# Sensor Coverage Planner Ground
sub_start_exploration_topic_ : /start_exploration
sub_terrain_map_topic_ : /terrain_map
sub_terrain_map_ext_topic_ : /terrain_map_ext
sub_state_estimation_topic_ : /state_estimation
sub_registered_scan_topic_ : /registered_scan     #/sensor_state_estimation
sub_coverage_boundary_topic_ : /sensor_coverage_planner/coverage_boundary
sub_viewpoint_boundary_topic_ : /navigation_boundary
sub_nogo_boundary_topic_ : /sensor_coverage_planner/nogo_boundary
sub_joystick_topic_ : /joy
sub_reset_waypoint_topic_ : /reset_waypoint
pub_exploration_finish_topic_ : exploration_finish
pub_runtime_breakdown_topic_ : runtime_breakdown
pub_runtime_topic_ : /runtime
pub_waypoint_topic_ : /way_point
pub_momentum_activation_count_topic_ : momentum_activation_count

kAutoStart : true
kRushHome : true
kUseTerrainHeight : false
kCheckTerrainCollision : true
kExtendWayPoint : true
kUseLineOfSightLookAheadPoint : true
kNoExplorationReturnHome : true
kExtendWayPointDistanceBig : 1.2
kExtendWayPointDistanceSmall : 0.3
kKeyposeCloudDwzFilterLeafSize : 0.2
kRushHomeDist : 10
kAtHomeDistThreshold : 0.5
kTerrainCollisionThreshold : 0.5
kLookAheadDistance : 2.5        # reading
kUseMomentum : false 
kDirectionChangeCounterThr : 3  #6
kDirectionNoChangeCounterThr : 2   #5
kResetWaypointJoystickButton : 0


# PlanningEnv
kUseFrontier : true
kFrontierClusterTolerance : 1.0
kFrontierClusterMinSize : 10
kUseCoverageBoundaryOnFrontier : false 
kUseCoverageBoundaryOnObjectSurface : false

# Rolling occupancy grid
rolling_occupancy_grid/resolution_x : 0.2
rolling_occupancy_grid/resolution_y : 0.2
rolling_occupancy_grid/resolution_z : 0.2

kSurfaceCloudDwzLeafSize : 0.1            # down size cloud
kCollisionCloudDwzLeafSize : 0.1
kKeyposeCloudStackNum : 5
# kPointCloudRowNum : 50
# kPointCloudColNum : 50
# kPointCloudLevelNum : 30
kPointCloudRowNum : 40
kPointCloudColNum : 40
kPointCloudLevelNum : 10

kMaxCellPointNum : 100000
kPointCloudCellSize : 4
# kPointCloudCellSize : 0.3
# kPointCloudCellHeight : 1.8
kPointCloudCellHeight : 0.2
kPointCloudManagerNeighborCellNum : 5
kCoverCloudZSqueezeRatio : 2.0

# KeyposeGraph
keypose_graph/kAddNodeMinDist : 1.0
keypose_graph/kAddNonKeyposeNodeMinDist : 0.5
keypose_graph/kAddEdgeConnectDistThr : 3.0
keypose_graph/kAddEdgeToLastKeyposeDistThr : 3.0
keypose_graph/kAddEdgeVerticalThreshold : 1.0
keypose_graph/kAddEdgeCollisionCheckResolution : 0.4
keypose_graph/kAddEdgeCollisionCheckRadius : 0.4
keypose_graph/kAddEdgeCollisionCheckPointNumThr : 1

# ViewPointManager
viewpoint_manager/number_x : 40
viewpoint_manager/number_y : 40
viewpoint_manager/number_z : 1
# viewpoint_manager/resolution_x : 1.2
viewpoint_manager/resolution_x : 0.2
# viewpoint_manager/resolution_y : 1.2
viewpoint_manager/resolution_y : 0.2
viewpoint_manager/resolution_z : 0.0
kConnectivityHeightDiffThr : 0.25   #0.4
kGreedyViewPointSampleRange : 3
kLocalPathOptimizationItrMax : 10
kViewPointCollisionMargin : 0.1
kViewPointCollisionMarginZPlus : 0.5
kViewPointCollisionMarginZMinus : 0.5
kCollisionGridZScale : 1.0
kCollisionGridResolutionX : 0.05
kCollisionGridResolutionY : 0.05
kCollisionGridResolutionZ : 0.0

kFreeOccupancyGridResolutionX : 0.2  #0.2
kFreeOccupancyGridResolutionY : 0.2
kFreeOccupancyGridResolutionZ : 0.0
kViewPointOccupancyGridMargin : 0.12

kCollisionPointThr : 1
kLineOfSightStopAtNearestObstacle : true
kViewPointHeightFromTerrain : 0.75
kViewPointHeightFromTerrainChangeThreshold : 0.6
kCheckDynamicObstacleCollision : false
kCollisionFrameCountMax : 3

kSensorRange : 1.5
kNeighborRange : 0.1
kCoverageOcclusionThr : 0.3
kCoverageDilationRadius : 1.0

# Grid World
kGridWorldXNum : 121
kGridWorldYNum : 121
kGridWorldZNum : 12
kGridWorldCellHeight : 0.6
kGridWorldNearbyGridNum : 5
kMinAddPointNumSmall : 40
kMinAddPointNumBig : 60
kMinAddFrontierPointNum : 5 #15
kCellExploringToCoveredThr : 1
kCellCoveredToExploringThr: 10
kCellExploringToAlmostCoveredThr: 10
kCellAlmostCoveredToExploringThr: 20
kCellUnknownToExploringThr: 1

# Visualization
kExploringSubspaceMarkerColorGradientAlpha : true
kExploringSubspaceMarkerColorMaxAlpha : 0.8
kExploringSubspaceMarkerColorR : 0.0
kExploringSubspaceMarkerColorG : 1.0
kExploringSubspaceMarkerColorB : 0.0
kExploringSubspaceMarkerColorA : 1.0
kLocalPlanningHorizonMarkerColorR : 0.0
kLocalPlanningHorizonMarkerColorG : 1.0
kLocalPlanningHorizonMarkerColorB : 0.0
kLocalPlanningHorizonMarkerColorA : 1.0
kLocalPlanningHorizonMarkerWidth : 0.05
kLocalPlanningHorizonHeight : 0.4